### ISSUE TITLE
Cannot show a blog with correct format

### ISSUE THREAD

**Issue by zjunweihit** [Simpleyyt/jekyll-jacman#1]
Hi,

When I set up the blog locally, I cannot show the blog as correct format, but the github can.
Do I need to setup something for local display?
Thanks.

**Comment by Simpleyyt** [comment]
There is a tutorial: [Setting up your GitHub Pages site locally with Jekyll](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/)

**Comment by zjunweihit** [comment]
I could setup jekyll and preview with other themes.
But this one will show unexpected format, like bigger font, toc doesn't list headers but the contents only locally.

do i need to setup hexo or sth else dependency?

**Comment by Simpleyyt** [comment]
You can post your _config.yml and screenshot here.

**Comment by Simpleyyt** [comment]
In addition, you can use the chrome develop tool to find what error occurred.

**Comment by zjunweihit** [comment]
the _config.yml is same as yours in github repo. The screenshot went wrong when uploading.

Now I work with hexo, which works locally and github.
Thanks all the same.
