### ISSUE TITLE
请教一下，url错误是怎么回事？

### ISSUE THREAD

**Issue by bantu4me** [Simpleyyt/jekyll-jacman#15]
你好，我尝试将你的项目fork过去。但是加载web资源的时候url好像不对。这是我的url
`/auassets/js/jquery-2.0.3.min.js `
我看你这边加载资源的url是下面这样的
`/jekyll-jacman/assets/js/jquery-2.0.3.min.js`
少了一个项目名称jekyll-jacman。导致所有资源都加载失败了。刚刚了解到jekyll，或许是我搜索关键字不对，没有在网上找到解决办法。不知道是不是哪里配置要改一下。如果看到请看看我这个问题。谢谢

**Comment by Simpleyyt** [comment]
解决了吗？

**Comment by bantu4me** [comment]
解决了，谢谢。在配置文件里面加上了assets的相对路径好了。之前尝试改了baseUrl没有用。谢谢
