### ISSUE TITLE
望添加其他第三方评论插件

### ISSUE THREAD

**Issue by 0bo** [Simpleyyt/jekyll-jacman#16]
多说挂了，disque墙了，希望可以添加其他第三方评论系统。

网易云跟帖貌似有jekyll直接可以用的代码，而且支持https吧，望添加。

**Comment by xinkunZ** [comment]
这玩意貌似很好加的，就算jekyll模板不支持通用的配置，你也可以直接在html中插入网易大法提供的js标签。在`_includes/_partial/post/comment.html`里，你可以看看我的

**Comment by Simpleyyt** [comment]
网易云跟帖有个小问题就是需要一级域名，虽然可以乱填，我可以试试。

**Comment by xinkunZ** [comment]
他们域名是可以乱填，不过有点智障，添加一次之后不能更改，而且万一你填了一个真实存在的，那么这个域名的站长就用不了

**Comment by Simpleyyt** [comment]
已经添加网易云贴。
