### ISSUE TITLE
con't comment article

### ISSUE THREAD

**Issue by RainflyRain** [Simpleyyt/jekyll-jacman#2]
Duoshuo_shortname and disqus_shortname, I have already set up the value in  _config.yml . but still can't comment.please help.

**Comment by Simpleyyt** [comment]
You can refer my __config.yml in my blog：https://github.com/Simpleyyt/simpleyyt.github.io. You can only set one of them, not both of them.

**Comment by Simpleyyt** [comment]
And I haven't test whether disqus work properly.
