### ISSUE TITLE
baseurl修改为空。但是网站内容还是您自己的？

### ISSUE THREAD

**Issue by 892768447** [Simpleyyt/jekyll-jacman#5]
beautiful

**Comment by Simpleyyt** [comment]
是在哪里搭建？

**Comment by 892768447** [comment]
3.1本地和coding上面，后来知道了，是那个分页的问题，解决了，就是回复上面友友的办法，现在还有个问题就是底部能显示邮箱图标，但是不显示其他的，网页右键查看代码。又有相应的html。但是图标就是不显示。晚点我再改改
