### ISSUE TITLE
Kramdown引擎更换问题

### ISSUE THREAD

**Issue by miaochiahao** [Simpleyyt/jekyll-jacman#6]
话说Github不再支持原来的Redcarpet了，我在配置文件里更换以后整个博客的主题全乱了==，二级标题显示不出来，而且高亮也没有。请问大家是怎么解决的？

**Comment by Simpleyyt** [comment]
是的 ~ 是markdown的语法问题  你必须严格按照kramdown的语法  比如说空格和空一行什么的  我还没有比较好的解决办法

**Comment by Simpleyyt** [comment]
Redcarpet只是warning 所以我不理他

**Comment by miaochiahao** [comment]
我刚才找了一个用kramdown写的博文看了下markdown文件，发现了我的几处格式错误。现在就剩下代码高亮问题啦。话说这东西不解决真的没问题么……说不定哪天就撒手不干了

**Comment by Simpleyyt** [comment]
我新推了一个分支 kramdown，把Markdown引擎换成了kramdown，把高亮换成了rough。

**Comment by miaochiahao** [comment]
我去看下,谢谢！！  ：)
