### ISSUE TITLE
主要页面全部404

### ISSUE THREAD

**Issue by sindrilin** [Simpleyyt/jekyll-jacman#7]
您好，能否分享一下您实例网站中的文章详情、分类筛选这些html文件呢？这些网页点击之后全部404搜索不到了

**Comment by Simpleyyt** [comment]
我看了你的__config.yml，应该把
baseurl: sindrilin.com
改成：
baseurl: http://sindrilin.com

**Comment by sindrilin** [comment]
谢谢，修改完成已经可以使用了
