### ISSUE TITLE
markdown语法布局问题

### ISSUE THREAD

**Issue by frandfeng** [Simpleyyt/jekyll-jacman#8]
在使用markdown语法时，shift键嵌入代码后，会发现，文字的颜色和背景的颜色很相似，均是黑色，从而导致看不到文字

**Comment by Simpleyyt** [comment]
那是你使用了 kramdown 引擎的原因，我的项目有个分支是专门使用 kramdown 引擎的，可以改一下：

https://github.com/Simpleyyt/jekyll-jacman/tree/kramdown

**Comment by frandfeng** [comment]
thanks, problem solved
